### ISSUE TITLE
DL24NoResponseError despite valid packets?

### ISSUE THREAD

**Issue by AndKe** [KrystianD/dl24-electronic-load#3]
$ dl24-manage -p /dev/ttyUSB0 read
Traceback (most recent call last):
  File "/home/andre/prog/PycharmProjects/mav-progs/venv/bin/dl24-manage", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/andre/prog/PycharmProjects/mav-progs/venv/lib/python3.12/site-packages/dl24/tools/manage/__main__.py", line 131, in main
    args.cmd(dl24, *args.cmd_args(args))
  File "/home/andre/prog/PycharmProjects/mav-progs/venv/lib/python3.12/site-packages/dl24/tools/manage/__main__.py", line 49, in read
    is_on = dl24.get_is_on()
            ^^^^^^^^^^^^^^^^
  File "/home/andre/prog/PycharmProjects/mav-progs/venv/lib/python3.12/site-packages/dl24/__init__.py", line 224, in get_is_on
    pa = self.read_value([IS_ON, 0, 0])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andre/prog/PycharmProjects/mav-progs/venv/lib/python3.12/site-packages/dl24/__init__.py", line 206, in read_value
    raise DL24NoResponseError
dl24.DL24NoResponseError: no response
(venv) andre@loke:~$ 

I see the load emitting those packets: 

![image](https://github.com/user-attachments/assets/4c34de6c-24f6-404d-ada5-48132956d09f)

And the program is sending this: 
![image](https://github.com/user-attachments/assets/bb9d8e8f-62fc-4bba-aeed-bd6ec3a0b949)

I am attaching the logic analyzer output so you can see for youself:
[DL24NoResponseError.zip](https://github.com/user-attachments/files/18229285/DL24NoResponseError.zip)

You can download the app (multiplatform) from saleae.com/downloads

**Comment by KrystianD** [comment]
Hi, few points:

1. The packets you are showing (and in the dump) are broadcast packets (start with 0xFF) only, not responses to the IS_ON request.
2. Broadcasts should be sent every second, but looks like in your dump sometimes it takes 2 seconds between subsequent packets which makes me think something is wrong somewhere.
3. Do you use USB-TTL adapter by soldering some headers to unpopulated pins on the DL24 board? Given the way it is connected internally to USB and BT chips, not all converters are strong enough to pull the chip's RX line down - resulting in µC not receiving requests from the upstream computer properly.

**Comment by AndKe** [comment]
The load is the 600W in-a-chassis with violet PCB's.
The controller pcb had this IC:
https://www.yunthinker.net/wp-content/uploads/2024/08/AC6328A_Datasheet-V1.0.pdf

It was communicating using async-serial at 9600bps on pin 7,8.   (I did not save that recording)
The BT connection worked with the "E-test" android app.  - as you said, before doing so, the FTDI could pull down only to only about 2.5v.
(I do not know what pin 2 (PA9) was used for, but I suspect it is the BT activity symbol on the LCD.)

I desoldered the IC, and connected a FTDI board instead.  Signals/levels are nice and clean (checked with an oscilloscope)
(that was before submitting this issue)

**Comment by KrystianD** [comment]
Ok, unfortunately I have no other ideas, it may be using different protocol or commands. You can try to intercept what original app is sending to it and adjust commands and/or protocol headers accordingly.

**Comment by AndKe** [comment]
Can you read my logic analyser files?  - I can re-solder it and capture everything from the boot till the E-test app connection and command if that helps.
I noticed that there were some traffic on both lines on boot.

**Comment by KrystianD** [comment]
I won't be able to support this because I don't have the device for testing, reverse engineering also takes quite lot of time.

Anyway, I encourage you to try yourself, it may be simple values change.

Yes, I do use Saleae so can read your dumps, you can post them here after you are done, but I can't promise I will be able to help.

**Comment by AndKe** [comment]
Hi, I found that TestController https://lygte-info.dk/project/TestControllerIntro%20UK.html#Load_devices  works well with it as-is, so I just reassembled it with the USB cable mod.
